const data = [
    {
        id: 1,
        categoryId: 1,
        modelo: "Flowers",
        price: "AR$ 15.000",
        img: "../assets/trajetiroalto.png",
        description: "Corpiño con sosten fijo estampado con tiras elásticas. Breteles regulables y bombacha ajustables con tiras. Las estampas de cada Bikini se hacen una por una, artesanalmente.",
        stock: 5, 
    },
    {
        id: 2,
        categoryId: 1,
        modelo: "Pop Woman",
        price: "AR$ 19.000",
        img: "../assets/popwoman.png",
        description: "Corpiño con breteles gruesos, con relleno. Estampado animal print , hay otro combinaciones de colores como azul, negro, gris.",
        stock: 7, 
    },
    {
        id: 3,
        categoryId: 1,
        modelo: "Point Woman",
        price: "AR$ 21.200",
        img: "../assets/pointwoman.png", 
        description: "Bikini color coral , con corpiño con push-up , la bombacha tiene detalle de hojas . Vienen en varios tonos y colores.",
        stock: 8, 
    },
    {
        id: 4,
        categoryId: 1,
        modelo: "Panter ",
        price: "AR$ 22.800",
        img:  "../assets/panterbikini.png",
        description: "Un modelo de bikini que viene con short, hay que diferentes colores , las tiras del corpiño son desmontrables.",
        stock: 9, 
    },
    {
        id: 5,
        categoryId: 1,
        modelo: "Blaslady",
        price: "AR$ 17.600",
        img: "../assets/blaslady.png",
        description: "Modelo con tiras finas tipo trikini , viene en varios tonos , tambien hay estampados lisos, la bombacha puede ser floreada o con estampado liso.",
        stock: 7, 
    },
    {
        id: 6,
        categoryId: 1,
        modelo: "Carribean",
        price: "AR$ 19.000",
        img: "../assets/bikinrosaynegra.png",
        description: "Corpiño bordo con bombacha floreada de tres tiras, hay varios estampados de bombacha y también estampados de corpiño lisos.",
        stock: 3, 
    },
    {
        id: 7,
        categoryId: 1,
        modelo: "Flower Bordeaux",
        price: "AR$ 22.600",
        img: "../assets/flowerbordeaux.png",
        description: "Estilo de trikini, con un detalle de una cinta que cruza, este mismo modelo esta en color negro , gris o blando.",
        stock: 12, 
    },
    {
        id: 8,
        categoryId: 1,
        modelo: "Sheet Dark Green",
        price: "AR$ 21.900",
        img: "../assets/hojasverdes.png",
        description: "Bikini de dos piezas, con un bombacha con hojas , este mismo modelo esta en color negro , gris o azul.",
        stock: 9, 
    },
    {
        id: 9,
        categoryId: 1,
        modelo: "Night straplees",
        price: "AR$ 29.000",
        img: "../assets/straplessblack.png",
        description: "Estilo de trikini, con un detalle de una cinta que cruza, este mismo modelo esta en color negro , gris o blando.",
        stock: 6, 
    },
    {
        id: 10,
        categoryId: 2,
        modelo: "Cactus men",
        price: "AR$ 26.000",
        img: "../assets/cactusmen.png",
        description: "modelo de malla para hombres con dibujo de cactus, con bolsillo interno  este mismo modelo tiene otros estampados .",
        stock: 6,    
    }
]

module.exports = {
    data,
}