const data = [
    {
        id: 1,
        categoryId: 1,
        modelo: "Flowers",
        price: "AR$ 15.000",
        img: "../assets/trajetiroalto.png",
        description: "Corpiño con sosten fijo estampado con tiras elásticas. Breteles regulables y bombacha ajustables con tiras. Las estampas de cada Bikini se hacen una por una, artesanalmente.",
        stock: 5, 
    },
    {
        id: 2,
        categoryId: 1,
        modelo: "Pop Woman",
        price: "AR$ 19.000",
        img: "../assets/popwoman.png",
        description: "Corpiño con breteles gruesos, con relleno. Estampado animal print , hay otro combinaciones de colores como azul, negro, gris.",
        stock: 7, 
    },
    {
        id: 3,
        categoryId: 1,
        modelo: "Point Woman",
        price: "AR$ 21.200",
        img: "../assets/pointwoman.png", 
        description: "Bikini color coral , con corpiño con push-up , la bombacha tiene detalle de hojas . Vienen en varios tonos y colores.",
        stock: 8, 
    },
    {
        id: 4,
        categoryId: 1,
        modelo: "Panter ",
        price: "AR$ 22.800",
        img:  "../assets/panterbikini.png",
        description: "Un modelo de bikini que viene con short, hay que diferentes colores , las tiras del corpiño son desmontrables.",
        stock: 9, 
    },
    {
        id: 5,
        categoryId: 1,
        modelo: "Blaslady",
        price: "AR$ 17.600",
        img: "../assets/blaslady.png",
        description: "Modelo con tiras finas tipo trikini , viene en varios tonos , tambien hay estampados lisos, la bombacha puede ser floreada o con estampado liso.",
        stock: 7, 
    },
    {
        id: 6,
        categoryId: 1,
        modelo: "Carribean",
        price: "AR$ 19.000",
        img: "../assets/bikinrosaynegra.png",
        description: "Corpiño bordo con bombacha floreada de tres tiras, hay varios estampados de bombacha y también estampados de corpiño lisos.",
        stock: 3, 
    },
    {
        id: 7,
        categoryId: 1,
        modelo: "Flower Bordeaux",
        price: "AR$ 22.600",
        img: "../assets/flowerbordeaux.png",
        description: "Estilo de trikini, con un detalle de una cinta que cruza, este mismo modelo esta en color negro , gris o blando.",
        stock: 12, 
    },
    {
        id: 8,
        categoryId: 1,
        modelo: "Sheet Dark Green",
        price: "AR$ 21.900",
        img: "../assets/hojasverdes.png",
        description: "Bikini de dos piezas, con un bombacha con hojas , este mismo modelo esta en color negro , gris o azul.",
        stock: 9, 
    },
    {
        id: 9,
        categoryId: 1,
        modelo: "Night straplees",
        price: "AR$ 29.000",
        img: "../assets/straplessblack.png",
        description: "Estilo de trikini, con un detalle de una cinta que cruza, este mismo modelo esta en color negro , gris o blando.",
        stock: 6, 
    },
    {
        id: 10,
        categoryId: 2,
        modelo: "Cactus men",
        price: "AR$ 26.000",
        img: "../assets/cactusmen.png",
        description: "Modelo de malla para hombres con dibujo de cactus, con bolsillo interno  este mismo modelo tiene otros estampados .",
        stock: 6,    
    },
    {
        id: 11,
        categoryId: 2,
        modelo: "Egyptianmen",
        price: "AR$ 17.800",
        img: "../assets/egyptian.png",
        description: "Modelo de malla para hombres con dibujos egipcios, con bolsillo interno  este mismo modelo tiene otros estampados, contiene estuche de guardado .",
        stock: 7,    
    },
    {
        id: 12,
        categoryId: 2,
        modelo: "Mandalawear",
        price: "AR$ 23.250",
        img: "../assets/mandala.png",
        description: "Modelo de malla para hombres con dibujos mandala, con bolsillo interno  este mismo modelo tiene otras combinaciones de colores.",
        stock: 7,    
    },
    {
        id: 13,
        categoryId: 2,
        modelo: "Tricolorwear",
        price: "AR$ 24.670",
        img: "../assets/trcolormen.jpg",
        description: "Modelo de malla para hombres con dibujos egipcios, con bolsillo interno  este mismo modelo tiene otros estampados, contiene estuche de guardado .",
        stock: 7,    
    },
    {
        id: 14,
        categoryId: 3,
        modelo: "Paw Patrol",
        price: "AR$ 15.140",
        img: "../assets/pawpatrolchild.png",
        description: "Modelo de malla para hombres con dibujos egipcios, con bolsillo interno  este mismo modelo tiene otros estampados, contiene estuche de guardado .",
        stock: 7,    
    },
    {
        id: 15,
        categoryId: 3,
        modelo: "Flower Child",
        price: "AR$ 15.340",
        img: "../assets/enterizaflornina.png",
        description: "Modelo de malla enteriza para niñas con dibujos de flores con la espalda cruzada, cste mismo modelo tiene otras comnbinaciones de colores.",
        stock: 5,    
    },
    {
        id: 16,
        categoryId: 3,
        modelo: "Blue Flamingo",
        price: "AR$ 14.640",
        img: "../assets/flamencochild.png",
        description: "Modelo de malla para niñas , consta de dos pieza  con dibujos de flamencos,  este mismo modelo tiene modelos lisos.",
        stock: 7,    
    },
    {
        id: 17,
        categoryId: 3,
        modelo: "Flower Child",
        price: "AR$ 16.530",
        img: "../assets/flowerchild.png",
        description: "Modelo de malla para niñas, con dibujos floreados, con moños en la parte de las tiras del corpiño, este mismo modelo tiene otros estampados.",
        stock: 7,    
    },
    {
        id: 18,
        categoryId: 3,
        modelo: "Salmonchildl",
        price: "AR$ 17.140",
        img: "../assets/salmonnina.png",
        description: "Modelo de malla para niñas con dibujos floreados, cuenta con dos piezas, el top puede ser de colores , verde, blanco o floreado como la bombacha.",
        stock: 7,    
    },
    {
        id: 19,
        categoryId: 3,
        modelo: "Shark Boy ",
        price: "AR$ 15.200",
        img: "../assets/sharkboy.png",
        description: "Modelo de malla para niños con dibujos de tiburones, especial para resguardar al niño de la expoision del sol, viene con gorro, que tambien viene en color azul.",
        stock: 7,    
    }
]

module.exports = {
    data,
}